import { TCountriesWithPhoneCode } from '../types';

export const continentsData: Record<string, string[]> = {
  Africa: [
    'Algeria',
    'Angola',
    'Benin',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cameroon',
    'Central African Republic',
    'Chad',
    'Comoros',
    'Congo',
    "Côte d'Ivoire",
    'Djibouti',
    'Egypt',
    'Equatorial Guinea',
    'Eritrea',
    'Eswatini',
    'Ethiopia',
    'Gabon',
    'Gambia',
    'Ghana',
    'Guinea',
    'Guinea-Bissau',
    'Kenya',
    'Lesotho',
    'Liberia',
    'Libya',
    'Madagascar',
    'Malawi',
    'Mali',
    'Mauritania',
    'Mauritius',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Niger',
    'Nigeria',
    'Rwanda',
    'Sao Tome and Principe',
    'Senegal',
    'Seychelles',
    'Sierra Leone',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Sudan',
    'Tanzania',
    'Togo',
    'Tunisia',
    'Uganda',
    'Zambia',
    'Zimbabwe',
  ],
  Asia: [
    'Afghanistan',
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Bhutan',
    'Brunei',
    'Cambodia',
    'China',
    'Cyprus',
    'Georgia',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Malaysia',
    'Maldives',
    'Mongolia',
    'Myanmar',
    'Nepal',
    'North Korea',
    'Oman',
    'Pakistan',
    'Palestine',
    'Philippines',
    'Qatar',
    'Russia',
    'Saudi Arabia',
    'Singapore',
    'South Korea',
    'Sri Lanka',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Timor-Leste',
    'Turkey',
    'Turkmenistan',
    'United Arab Emirates',
    'Uzbekistan',
    'Vietnam',
    'Yemen',
  ],
  Europe: [
    'Albania',
    'Andorra',
    'Austria',
    'Belarus',
    'Belgium',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Czech Republic',
    'Denmark',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iceland',
    'Ireland',
    'Italy',
    'Kosovo',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Moldova',
    'Monaco',
    'Montenegro',
    'Netherlands',
    'North Macedonia',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'San Marino',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'Ukraine',
    'United Kingdom',
    'Vatican City',
  ],
  NorthAmerica: [
    'Antigua and Barbuda',
    'Bahamas',
    'Barbados',
    'Belize',
    'Canada',
    'Costa Rica',
    'Cuba',
    'Dominica',
    'Dominican Republic',
    'El Salvador',
    'Grenada',
    'Guatemala',
    'Haiti',
    'Honduras',
    'Jamaica',
    'Mexico',
    'Nicaragua',
    'Panama',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Trinidad and Tobago',
    'United States',
  ],
  SouthAmerica: [
    'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela',
  ],
  Oceania: [
    'Australia',
    'Fiji',
    'Kiribati',
    'Marshall Islands',
    'Micronesia',
    'Nauru',
    'New Zealand',
    'Palau',
    'Papua New Guinea',
    'Samoa',
    'Solomon Islands',
    'Tonga',
    'Tuvalu',
    'Vanuatu',
  ],
} as const;

export const getTotalCountries = (): number => {
  return getTotalCountriesPerContinent()['All'];
};

export const getTotalCountriesPerContinent = () => {
  const continents: Record<string, number> = {};
  let total = 0;

  for (const continent in continentsData) {
    continents[continent] = continentsData[continent].length;
    total += continentsData[continent].length;
  }

  continents['All'] = total;

  return continents;
};

export const countriesData = Object.values(continentsData).flat();

export const countriesWithPhoneCode: TCountriesWithPhoneCode[] = [
  { name: 'Algeria', code: 'DZ', mobileCode: '+213' },
  { name: 'Angola', code: 'AO', mobileCode: '+244' },
  { name: 'Benin', code: 'BJ', mobileCode: '+229' },
  { name: 'Botswana', code: 'BW', mobileCode: '+267' },
  { name: 'Burkina Faso', code: 'BF', mobileCode: '+226' },
  { name: 'Burundi', code: 'BI', mobileCode: '+257' },
  { name: 'Cabo Verde', code: 'CV', mobileCode: '+238' },
  { name: 'Cameroon', code: 'CM', mobileCode: '+237' },
  { name: 'Central African Republic', code: 'CF', mobileCode: '+236' },
  { name: 'Chad', code: 'TD', mobileCode: '+235' },
  { name: 'Comoros', code: 'KM', mobileCode: '+269' },
  { name: 'Congo', code: 'CG', mobileCode: '+242' },
  { name: "Côte d'Ivoire", code: 'CI', mobileCode: '+225' },
  { name: 'Djibouti', code: 'DJ', mobileCode: '+253' },
  { name: 'Egypt', code: 'EG', mobileCode: '+20' },
  { name: 'Equatorial Guinea', code: 'GQ', mobileCode: '+240' },
  { name: 'Eritrea', code: 'ER', mobileCode: '+291' },
  { name: 'Eswatini', code: 'SZ', mobileCode: '+268' },
  { name: 'Ethiopia', code: 'ET', mobileCode: '+251' },
  { name: 'Gabon', code: 'GA', mobileCode: '+241' },
  { name: 'Gambia', code: 'GM', mobileCode: '+220' },
  { name: 'Ghana', code: 'GH', mobileCode: '+233' },
  { name: 'Guinea', code: 'GN', mobileCode: '+224' },
  { name: 'Guinea-Bissau', code: 'GW', mobileCode: '+245' },
  { name: 'Kenya', code: 'KE', mobileCode: '+254' },
  { name: 'Lesotho', code: 'LS', mobileCode: '+266' },
  { name: 'Liberia', code: 'LR', mobileCode: '+231' },
  { name: 'Libya', code: 'LY', mobileCode: '+218' },
  { name: 'Madagascar', code: 'MG', mobileCode: '+261' },
  { name: 'Malawi', code: 'MW', mobileCode: '+265' },
  { name: 'Mali', code: 'ML', mobileCode: '+223' },
  { name: 'Mauritania', code: 'MR', mobileCode: '+222' },
  { name: 'Mauritius', code: 'MU', mobileCode: '+230' },
  { name: 'Morocco', code: 'MA', mobileCode: '+212' },
  { name: 'Mozambique', code: 'MZ', mobileCode: '+258' },
  { name: 'Namibia', code: 'NA', mobileCode: '+264' },
  { name: 'Niger', code: 'NE', mobileCode: '+227' },
  { name: 'Nigeria', code: 'NG', mobileCode: '+234' },
  { name: 'Rwanda', code: 'RW', mobileCode: '+250' },
  { name: 'Sao Tome and Principe', code: 'ST', mobileCode: '+239' },
  { name: 'Senegal', code: 'SN', mobileCode: '+221' },
  { name: 'Seychelles', code: 'SC', mobileCode: '+248' },
  { name: 'Sierra Leone', code: 'SL', mobileCode: '+232' },
  { name: 'Somalia', code: 'SO', mobileCode: '+252' },
  { name: 'South Africa', code: 'ZA', mobileCode: '+27' },
  { name: 'South Sudan', code: 'SS', mobileCode: '+211' },
  { name: 'Sudan', code: 'SD', mobileCode: '+249' },
  { name: 'Tanzania', code: 'TZ', mobileCode: '+255' },
  { name: 'Togo', code: 'TG', mobileCode: '+228' },
  { name: 'Tunisia', code: 'TN', mobileCode: '+216' },
  { name: 'Uganda', code: 'UG', mobileCode: '+256' },
  { name: 'Zambia', code: 'ZM', mobileCode: '+260' },
  { name: 'Zimbabwe', code: 'ZW', mobileCode: '+263' },
  { name: 'Afghanistan', code: 'AF', mobileCode: '+93' },
  { name: 'Armenia', code: 'AM', mobileCode: '+374' },
  { name: 'Azerbaijan', code: 'AZ', mobileCode: '+994' },
  { name: 'Bahrain', code: 'BH', mobileCode: '+973' },
  { name: 'Bangladesh', code: 'BD', mobileCode: '+880' },
  { name: 'Bhutan', code: 'BT', mobileCode: '+975' },
  { name: 'Brunei', code: 'BN', mobileCode: '+673' },
  { name: 'Cambodia', code: 'KH', mobileCode: '+855' },
  { name: 'China', code: 'CN', mobileCode: '+86' },
  { name: 'Cyprus', code: 'CY', mobileCode: '+357' },
  { name: 'Georgia', code: 'GE', mobileCode: '+995' },
  { name: 'India', code: 'IN', mobileCode: '+91' },
  { name: 'Indonesia', code: 'ID', mobileCode: '+62' },
  { name: 'Iran', code: 'IR', mobileCode: '+98' },
  { name: 'Iraq', code: 'IQ', mobileCode: '+964' },
  { name: 'Japan', code: 'JP', mobileCode: '+81' },
  { name: 'Jordan', code: 'JO', mobileCode: '+962' },
  { name: 'Kazakhstan', code: 'KZ', mobileCode: '+7' },
  { name: 'Kuwait', code: 'KW', mobileCode: '+965' },
  { name: 'Kyrgyzstan', code: 'KG', mobileCode: '+996' },
  { name: 'Laos', code: 'LA', mobileCode: '+856' },
  { name: 'Lebanon', code: 'LB', mobileCode: '+961' },
  { name: 'Malaysia', code: 'MY', mobileCode: '+60' },
  { name: 'Maldives', code: 'MV', mobileCode: '+960' },
  { name: 'Mongolia', code: 'MN', mobileCode: '+976' },
  { name: 'Myanmar', code: 'MM', mobileCode: '+95' },
  { name: 'Nepal', code: 'NP', mobileCode: '+977' },
  { name: 'North Korea', code: 'KP', mobileCode: '+850' },
  { name: 'Oman', code: 'OM', mobileCode: '+968' },
  { name: 'Pakistan', code: 'PK', mobileCode: '+92' },
  { name: 'Palestine', code: 'PS', mobileCode: '+970' },
  { name: 'Philippines', code: 'PH', mobileCode: '+63' },
  { name: 'Qatar', code: 'QA', mobileCode: '+974' },
  { name: 'Russia', code: 'RU', mobileCode: '+7' },
  { name: 'Saudi Arabia', code: 'SA', mobileCode: '+966' },
  { name: 'Singapore', code: 'SG', mobileCode: '+65' },
  { name: 'South Korea', code: 'KR', mobileCode: '+82' },
  { name: 'Sri Lanka', code: 'LK', mobileCode: '+94' },
  { name: 'Syria', code: 'SY', mobileCode: '+963' },
  { name: 'Taiwan', code: 'TW', mobileCode: '+886' },
  { name: 'Tajikistan', code: 'TJ', mobileCode: '+992' },
  { name: 'Thailand', code: 'TH', mobileCode: '+66' },
  { name: 'Timor-Leste', code: 'TL', mobileCode: '+670' },
  { name: 'Turkey', code: 'TR', mobileCode: '+90' },
  { name: 'Turkmenistan', code: 'TM', mobileCode: '+993' },
  { name: 'United Arab Emirates', code: 'AE', mobileCode: '+971' },
  { name: 'Uzbekistan', code: 'UZ', mobileCode: '+998' },
  { name: 'Vietnam', code: 'VN', mobileCode: '+84' },
  { name: 'Yemen', code: 'YE', mobileCode: '+967' },
  { name: 'Albania', code: 'AL', mobileCode: '+355' },
  { name: 'Andorra', code: 'AD', mobileCode: '+376' },
  { name: 'Austria', code: 'AT', mobileCode: '+43' },
  { name: 'Belarus', code: 'BY', mobileCode: '+375' },
  { name: 'Belgium', code: 'BE', mobileCode: '+32' },
  { name: 'Bosnia and Herzegovina', code: 'BA', mobileCode: '+387' },
  { name: 'Bulgaria', code: 'BG', mobileCode: '+359' },
  { name: 'Croatia', code: 'HR', mobileCode: '+385' },
  { name: 'Czech Republic', code: 'CZ', mobileCode: '+420' },
  { name: 'Denmark', code: 'DK', mobileCode: '+45' },
  { name: 'Estonia', code: 'EE', mobileCode: '+372' },
  { name: 'Finland', code: 'FI', mobileCode: '+358' },
  { name: 'France', code: 'FR', mobileCode: '+33' },
  { name: 'Germany', code: 'DE', mobileCode: '+49' },
  { name: 'Greece', code: 'GR', mobileCode: '+30' },
  { name: 'Hungary', code: 'HU', mobileCode: '+36' },
  { name: 'Iceland', code: 'IS', mobileCode: '+354' },
  { name: 'Ireland', code: 'IE', mobileCode: '+353' },
  { name: 'Italy', code: 'IT', mobileCode: '+39' },
  { name: 'Kosovo', code: 'XK', mobileCode: '+383' },
  { name: 'Latvia', code: 'LV', mobileCode: '+371' },
  { name: 'Liechtenstein', code: 'LI', mobileCode: '+423' },
  { name: 'Lithuania', code: 'LT', mobileCode: '+370' },
  { name: 'Luxembourg', code: 'LU', mobileCode: '+352' },
  { name: 'Malta', code: 'MT', mobileCode: '+356' },
  { name: 'Moldova', code: 'MD', mobileCode: '+373' },
  { name: 'Monaco', code: 'MC', mobileCode: '+377' },
  { name: 'Montenegro', code: 'ME', mobileCode: '+382' },
  { name: 'Netherlands', code: 'NL', mobileCode: '+31' },
  { name: 'North Macedonia', code: 'MK', mobileCode: '+389' },
  { name: 'Norway', code: 'NO', mobileCode: '+47' },
  { name: 'Poland', code: 'PL', mobileCode: '+48' },
  { name: 'Portugal', code: 'PT', mobileCode: '+351' },
  { name: 'Romania', code: 'RO', mobileCode: '+40' },
  { name: 'San Marino', code: 'SM', mobileCode: '+378' },
  { name: 'Serbia', code: 'RS', mobileCode: '+381' },
  { name: 'Slovakia', code: 'SK', mobileCode: '+421' },
  { name: 'Slovenia', code: 'SI', mobileCode: '+386' },
  { name: 'Spain', code: 'ES', mobileCode: '+34' },
  { name: 'Sweden', code: 'SE', mobileCode: '+46' },
  { name: 'Switzerland', code: 'CH', mobileCode: '+41' },
  { name: 'Ukraine', code: 'UA', mobileCode: '+380' },
  { name: 'United Kingdom', code: 'GB', mobileCode: '+44' },
  { name: 'Vatican City', code: 'VA', mobileCode: '+379' },
  { name: 'Antigua and Barbuda', code: 'AG', mobileCode: '+1' },
  { name: 'Bahamas', code: 'BS', mobileCode: '+1' },
  { name: 'Barbados', code: 'BB', mobileCode: '+1' },
  { name: 'Belize', code: 'BZ', mobileCode: '+501' },
  { name: 'Canada', code: 'CA', mobileCode: '+1' },
  { name: 'Costa Rica', code: 'CR', mobileCode: '+506' },
  { name: 'Cuba', code: 'CU', mobileCode: '+53' },
  { name: 'Dominica', code: 'DM', mobileCode: '+1' },
  { name: 'Dominican Republic', code: 'DO', mobileCode: '+1' },
  { name: 'El Salvador', code: 'SV', mobileCode: '+503' },
  { name: 'Grenada', code: 'GD', mobileCode: '+1' },
  { name: 'Guatemala', code: 'GT', mobileCode: '+502' },
  { name: 'Haiti', code: 'HT', mobileCode: '+509' },
  { name: 'Honduras', code: 'HN', mobileCode: '+504' },
  { name: 'Jamaica', code: 'JM', mobileCode: '+1' },
  { name: 'Mexico', code: 'MX', mobileCode: '+52' },
  { name: 'Nicaragua', code: 'NI', mobileCode: '+505' },
  { name: 'Panama', code: 'PA', mobileCode: '+507' },
  { name: 'Saint Kitts and Nevis', code: 'KN', mobileCode: '+1' },
  { name: 'Saint Lucia', code: 'LC', mobileCode: '+1' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', mobileCode: '+1' },
  { name: 'Trinidad and Tobago', code: 'TT', mobileCode: '+1' },
  { name: 'United States', code: 'US', mobileCode: '+1' },
  { name: 'Argentina', code: 'AR', mobileCode: '+54' },
  { name: 'Bolivia', code: 'BO', mobileCode: '+591' },
  { name: 'Brazil', code: 'BR', mobileCode: '+55' },
  { name: 'Chile', code: 'CL', mobileCode: '+56' },
  { name: 'Colombia', code: 'CO', mobileCode: '+57' },
  { name: 'Ecuador', code: 'EC', mobileCode: '+593' },
  { name: 'Guyana', code: 'GY', mobileCode: '+592' },
  { name: 'Paraguay', code: 'PY', mobileCode: '+595' },
  { name: 'Peru', code: 'PE', mobileCode: '+51' },
  { name: 'Suriname', code: 'SR', mobileCode: '+597' },
  { name: 'Uruguay', code: 'UY', mobileCode: '+598' },
  { name: 'Venezuela', code: 'VE', mobileCode: '+58' },
  { name: 'Australia', code: 'AU', mobileCode: '+61' },
  { name: 'Fiji', code: 'FJ', mobileCode: '+679' },
  { name: 'Kiribati', code: 'KI', mobileCode: '+686' },
  { name: 'Marshall Islands', code: 'MH', mobileCode: '+692' },
  { name: 'Micronesia', code: 'FM', mobileCode: '+691' },
  { name: 'Nauru', code: 'NR', mobileCode: '+674' },
  { name: 'New Zealand', code: 'NZ', mobileCode: '+64' },
  { name: 'Palau', code: 'PW', mobileCode: '+680' },
  { name: 'Papua New Guinea', code: 'PG', mobileCode: '+675' },
  { name: 'Samoa', code: 'WS', mobileCode: '+685' },
  { name: 'Solomon Islands', code: 'SB', mobileCode: '+677' },
  { name: 'Tonga', code: 'TO', mobileCode: '+676' },
  { name: 'Tuvalu', code: 'TV', mobileCode: '+688' },
  { name: 'Vanuatu', code: 'VU', mobileCode: '+678' },
];
