export const countryToCodeMap: Record<string, string> = {
  Algeria: 'DZ',
  Angola: 'AO',
  Benin: 'BJ',
  Botswana: 'BW',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  'Cabo Verde': 'CV',
  Cameroon: 'CM',
  'Central African Republic': 'CF',
  Chad: 'TD',
  Comoros: 'KM',
  Congo: 'CG',
  "Côte d'Ivoire": 'CI',
  Djibouti: 'DJ',
  Egypt: 'EG',
  'Equatorial Guinea': 'GQ',
  Eritrea: 'ER',
  Eswatini: 'SZ',
  Ethiopia: 'ET',
  Gabon: 'GA',
  Gambia: 'GM',
  Ghana: 'GH',
  Guinea: 'GN',
  'Guinea-Bissau': 'GW',
  Kenya: 'KE',
  Lesotho: 'LS',
  Liberia: 'LR',
  Libya: 'LY',
  Madagascar: 'MG',
  Malawi: 'MW',
  Mali: 'ML',
  Mauritania: 'MR',
  Mauritius: 'MU',
  Morocco: 'MA',
  Mozambique: 'MZ',
  Namibia: 'NA',
  Niger: 'NE',
  Nigeria: 'NG',
  Rwanda: 'RW',
  'Sao Tome and Principe': 'ST',
  Senegal: 'SN',
  Seychelles: 'SC',
  'Sierra Leone': 'SL',
  Somalia: 'SO',
  'South Africa': 'ZA',
  'South Sudan': 'SS',
  Sudan: 'SD',
  Tanzania: 'TZ',
  Togo: 'TG',
  Tunisia: 'TN',
  Uganda: 'UG',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
  Afghanistan: 'AF',
  Armenia: 'AM',
  Azerbaijan: 'AZ',
  Bahrain: 'BH',
  Bangladesh: 'BD',
  Bhutan: 'BT',
  Brunei: 'BN',
  Cambodia: 'KH',
  China: 'CN',
  Cyprus: 'CY',
  Georgia: 'GE',
  India: 'IN',
  Indonesia: 'ID',
  Iran: 'IR',
  Iraq: 'IQ',
  Japan: 'JP',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kuwait: 'KW',
  Kyrgyzstan: 'KG',
  Laos: 'LA',
  Lebanon: 'LB',
  Malaysia: 'MY',
  Maldives: 'MV',
  Mongolia: 'MN',
  Myanmar: 'MM',
  Nepal: 'NP',
  'North Korea': 'KP',
  Oman: 'OM',
  Pakistan: 'PK',
  Palestine: 'PS',
  Philippines: 'PH',
  Qatar: 'QA',
  Russia: 'RU',
  'Saudi Arabia': 'SA',
  Singapore: 'SG',
  'South Korea': 'KR',
  'Sri Lanka': 'LK',
  Syria: 'SY',
  Taiwan: 'TW',
  Tajikistan: 'TJ',
  Thailand: 'TH',
  'Timor-Leste': 'TL',
  Turkey: 'TR',
  Turkmenistan: 'TM',
  'United Arab Emirates': 'AE',
  Uzbekistan: 'UZ',
  Vietnam: 'VN',
  Yemen: 'YE',
  Albania: 'AL',
  Andorra: 'AD',
  Austria: 'AT',
  Belarus: 'BY',
  Belgium: 'BE',
  'Bosnia and Herzegovina': 'BA',
  Bulgaria: 'BG',
  Croatia: 'HR',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  Estonia: 'EE',
  Finland: 'FI',
  France: 'FR',
  Germany: 'DE',
  Greece: 'GR',
  Hungary: 'HU',
  Iceland: 'IS',
  Ireland: 'IE',
  Italy: 'IT',
  Kosovo: 'XK',
  Latvia: 'LV',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Malta: 'MT',
  Moldova: 'MD',
  Monaco: 'MC',
  Montenegro: 'ME',
  Netherlands: 'NL',
  'North Macedonia': 'MK',
  Norway: 'NO',
  Poland: 'PL',
  Portugal: 'PT',
  Romania: 'RO',
  'San Marino': 'SM',
  Serbia: 'RS',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  Ukraine: 'UA',
  'United Kingdom': 'GB',
  'Vatican City': 'VA',
  'Antigua and Barbuda': 'AG',
  Bahamas: 'BS',
  Barbados: 'BB',
  Belize: 'BZ',
  Canada: 'CA',
  'Costa Rica': 'CR',
  Cuba: 'CU',
  Dominica: 'DM',
  'Dominican Republic': 'DO',
  'El Salvador': 'SV',
  Grenada: 'GD',
  Guatemala: 'GT',
  Haiti: 'HT',
  Honduras: 'HN',
  Jamaica: 'JM',
  Mexico: 'MX',
  Nicaragua: 'NI',
  Panama: 'PA',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Vincent and the Grenadines': 'VC',
  'Trinidad and Tobago': 'TT',
  'United States': 'US',
  Argentina: 'AR',
  Bolivia: 'BO',
  Brazil: 'BR',
  Chile: 'CL',
  Colombia: 'CO',
  Ecuador: 'EC',
  Guyana: 'GY',
  Paraguay: 'PY',
  Peru: 'PE',
  Suriname: 'SR',
  Uruguay: 'UY',
  Venezuela: 'VE',
  Australia: 'AU',
  Fiji: 'FJ',
  Kiribati: 'KI',
  'Marshall Islands': 'MH',
  Micronesia: 'FM',
  Nauru: 'NR',
  'New Zealand': 'NZ',
  Palau: 'PW',
  'Papua New Guinea': 'PG',
  Samoa: 'WS',
  'Solomon Islands': 'SB',
  Tonga: 'TO',
  Tuvalu: 'TV',
  Vanuatu: 'VU',
} as const;
